drop table students;
drop table groups;
drop table students_log;

1)
create table groups (
  id number,
  name varchar2(50),
  c_val number,
  constraint pk_groups primary key (id)
);

create table students (
  id number,
  name varchar2(100),
  group_id number,
  constraint pk_students primary key (id)
);

4)
create table students_log (
    id number generated by default as identity,
    username varchar2(100) not null ,
    date_of_action date not null ,
    operation varchar2(10) not null ,
    stud_id number not null ,
    stud_name varchar2(100) not null ,
    stud_group_id number not null
);


